CREATE TABLE IF NOT EXISTS actor
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255) NOT NULL,
    birthday    DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS director
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255) NOT NULL,
    birthday    DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS genre
(
    id   VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS country
(
    id   VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS movie
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(255)                         NOT NULL,
    production_date DATE                                 NOT NULL,
    country_id      VARCHAR(255) REFERENCES country (id) NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255),
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS comment
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    author_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    movie_id  BIGINT NOT NULL REFERENCES movie (id) ON DELETE CASCADE,
    text      TEXT   NOT NULL,
    rating    FLOAT  NOT NULL CHECK ( rating BETWEEN 0.0 AND 5.0)
);

CREATE TABLE IF NOT EXISTS movie_genres
(
    movie_id BIGINT REFERENCES movie (id) ON DELETE CASCADE,
    genre_id VARCHAR(255) REFERENCES genre (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS movie_directors
(
    movie_id    BIGINT REFERENCES movie (id) ON DELETE CASCADE,
    director_id BIGINT REFERENCES director (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS movie_actors
(
    movie_id BIGINT REFERENCES movie (id) ON DELETE CASCADE,
    actor_id BIGINT REFERENCES actor (id) ON DELETE CASCADE
);
